baseURL = "https://stamilselvan.github.io/"
title = "Bits and Stories"

theme = "puppet"

copyright = " "
paginate = 3
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "tech"
name = "Tech"
url = "/series/Tech/"
weight = 10
[[menu.main]]
identifier = "finance"
name = "Finance"
url = "/series/Finance/"
weight = 20
[[menu.main]]
identifier = "others"
name = "Others"
url = "/series/Others/"
weight = 30
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 50
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 60

[params]
custom_js = ["js/jquery.tablesorter.min.js", "js/custom.js"] 
custom_css = ["css/custom.css", "css/theme.default.min.css"] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]
useFaviconGenerator = true

[params.sidebar]
enable = false
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
bio = "a personal website"

# See https://giscus.app/
[params.giscus]
enable = true
repo = "stamilselvan/stamilselvan.github.io"
repo_id = "R_kgDOKcGxBg"
category = "General"
category_id = "DIC_kwDOKcGxBs4CaNxm"
mapping="pathname"
strict="0"
reactions-enabled="1"
input_position = "top"
theme = "light_tritanopia"
lang = "en"

